FROM debian:bullseye

# allow fetching source packages
RUN echo "deb-src http://deb.debian.org/debian/ bullseye main" >> /etc/apt/sources.list

# prepare
RUN apt-get update -qq

# install build essentials
RUN apt-get install -yq build-essential

# install PackageKit-Qt dependencies
RUN apt-get build-dep -yq packagekit-qt
RUN apt-get install -yq cmake ninja-build

# finish
RUN mkdir /build
WORKDIR /build
